### PR TITLE
Update clang-format and add CI formatting checks

### PR DESCRIPTION
**Pull request by aaronfranke**
This PR does several things:

* Update `.clang-format` to more closely match the current Godot master branch.

* Add CI checks for clang-format via GitHub Actions, so GitHub will run clang-format on commits and PRs.

* Add CI checks for file formatting, similar to the above. It checks that text files are POSIX-compliant.

* The second commit is just running the scripts added in the first commit.

### CODE REVIEW

**Comment by ChristophHaag** [comment]
Thanks for the PR. The change to clang format looks good, but would it be possible to exclude `openxr_loader_windows` from clang-formatting?

**Comment by aaronfranke** [comment]
@ChristophHaag Sure thing, I just did this. However, can you please point me to where the upstream files are so that I can apply formatting there? It would also be really nice to put README.md files in those folders to indicate where the upstream files are.

**Comment by ChristophHaag** [comment]
Thanks, the amount of changed lines looks better. :)

The openxr_loader_windows/1.0.9 directory contains a copy of an extracted build of the openxr loader from one of the zip files at https://github.com/KhronosGroup/OpenXR-SDK/releases

The headers are part of the OpenXR-SDK https://github.com/KhronosGroup/OpenXR-SDK/tree/master/include/openxr, more specifically they are generated from the OpenXR xml registry from the OpenXR-SDK-Source project https://github.com/KhronosGroup/OpenXR-SDK-Source. I don't think they will be reformatted without a good reason.

@BastiaanOlij any problems with formatting project source files like this? Seems to mostly remove empty indents.

**Comment by BastiaanOlij** [comment]
Yes this is going to be hell, 

Don't get me wrong, many thanks @aaronfranke , love that you're doing this but I think we need to hold off with this until all my Windows work is merged and then do the formatting ontop of that. Else I'm going to spend days of redoing stuff as the merge logic is going to completely spit the dummy on me.

**Comment by aaronfranke** [comment]
@BastiaanOlij No problem, it is extremely trivial to re-run the script.

Please continue with your work and then just let me know and I'll rebase this.

**Comment by BastiaanOlij** [comment]
> 
> @BastiaanOlij No problem, it is extremely trivial to re-run the script.
> 
> Please continue with your work and then just let me know and I'll rebase this.

Thanks dude! And thanks for helping out :)

**Comment by BastiaanOlij** [comment]
@ChristophHaag we should merge this I think? The other PRs are pretty small so shouldn't be hard to re-base them (famous last words), I think it makes sense to have this in place.

**Comment by ChristophHaag** [comment]
Yes, we can do this first if you want.

**Pull request merged**
