### PR TITLE
Skip render when xrLocateViews returns invalid pose

### PR DESCRIPTION
**Pull request by ChristophHaag**
Invalid pose means that the view pose quaternion may not be a valid (normalized) quaternion, which means xrEndFrame() will fail when supplied our projection layer with this view pose.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Also important here is if we are retrieving the pose when there is none, we either reuse the last pose or use an identify matrix. Even if we don't have any point in rendering output Godot will still process the frame and could run into trouble processing the scene data. The poses after all do update the camera position and controller positions.

**Comment by BastiaanOlij** [comment]
Ok this now breaks with all the changes I've done, Christoph you mind having a look at it? You might need to redo your changes.

**Comment by ChristophHaag** [comment]
`godot_arvr_get_transform_for_eye()` makes sure to return an identity transform when `get_view_transform()` returns false, there shouldn't be a problem.

**Comment by BastiaanOlij** [comment]
Looks good to me, merge it?

**Pull request merged**
